"""Coaching engine: phase progression, daily actions, and the coach's voice.

Phase logic and streak tracking are deterministic. The coaching message is
generated by Claude when ANTHROPIC_API_KEY (or an `ant auth login` profile)
is available, with a rule-based fallback so the prototype runs offline.
"""

import os

PHASE_SLEEP = "sleep"
PHASE_HABIT = "habit"
PHASE_GOAL = "goal"

PHASE_LABELS = {
    PHASE_SLEEP: "Phase 1 — Fix your sleep",
    PHASE_HABIT: "Phase 2 — Swap the habit",
    PHASE_GOAL: "Phase 3 — Your long-term goal",
}

# Graduation criteria (see BRAINSTORM.md)
SLEEP_WINDOW, SLEEP_REQUIRED = 7, 5      # hit sleep target 5 of last 7 days
HABIT_WINDOW, HABIT_REQUIRED = 14, 10    # habit swap 10 of last 14 days


def determine_phase(checkins: list[dict], sleep_target: float) -> str:
    """checkins are newest-first. Phases build on each other; a sleep
    regression pulls the user back to phase 1."""
    recent = checkins[:SLEEP_WINDOW]
    sleep_ok = (
        len(recent) >= SLEEP_REQUIRED
        and sum(1 for c in recent if c["sleep_hours"] >= sleep_target) >= SLEEP_REQUIRED
    )
    if not sleep_ok:
        return PHASE_SLEEP

    habit_recent = [c for c in checkins[:HABIT_WINDOW] if c["habit_replaced"] is not None]
    habit_ok = sum(1 for c in habit_recent if c["habit_replaced"]) >= HABIT_REQUIRED
    return PHASE_GOAL if habit_ok else PHASE_HABIT


def streaks(checkins: list[dict], sleep_target: float) -> dict:
    """Current consecutive-day streaks, newest-first input."""
    s = {"sleep": 0, "habit": 0, "goal": 0}
    for c in checkins:
        if c["sleep_hours"] >= sleep_target:
            s["sleep"] += 1
        else:
            break
    for c in checkins:
        if c["habit_replaced"]:
            s["habit"] += 1
        else:
            break
    for c in checkins:
        if c["goal_action_done"]:
            s["goal"] += 1
        else:
            break
    return s


def _default_action(phase: str, profile: dict) -> str:
    hobby = profile["replacement_hobby"]
    if phase == PHASE_SLEEP:
        return (
            f"Tonight: screens away 30 minutes before bed, aim for "
            f"{profile['sleep_target_hours']:g} hours. That's the whole assignment."
        )
    if phase == PHASE_HABIT:
        return (
            f"When you feel the pull toward {profile['bad_habit']}, do 15 minutes of "
            f"{hobby} instead. Just 15 — you can stop after."
        )
    if profile["long_term_goal"] == "lose_weight":
        return (
            "One swap today: replace a single sugary drink or snack with water or fruit. "
            "No diet overhaul — one swap."
        )
    if profile["long_term_goal"] == "learn_skill":
        detail = profile["goal_detail"] or "your skill"
        return f"20 focused minutes on {detail} today. Set a timer, stop when it rings."
    return "Take a 20-minute walk today, ideally outside."


def _fallback_message(phase: str, profile: dict, checkin: dict, strk: dict) -> str:
    name = profile["name"]
    target = profile["sleep_target_hours"]
    hours = checkin["sleep_hours"]
    if phase == PHASE_SLEEP:
        if hours >= target:
            return (
                f"Nice, {name} — {hours:g}h of sleep hits your target. "
                f"That's {strk['sleep']} night(s) in a row. Keep the same bedtime tonight."
            )
        return (
            f"{hours:g}h is under your {target:g}h target, {name} — no guilt, it's just "
            "data. Tonight we make it slightly easier, not perfect."
        )
    if phase == PHASE_HABIT:
        if checkin["habit_replaced"]:
            return (
                f"You chose {profile['replacement_hobby']} over {profile['bad_habit']} — "
                f"that's the whole game, {name}. Streak: {strk['habit']} day(s)."
            )
        return (
            f"The {profile['bad_habit']} won today — that happens. The plan doesn't "
            "change: same tiny swap tomorrow."
        )
    if checkin["goal_action_done"]:
        return (
            f"Goal action done — {strk['goal']} day(s) straight. Slow and repeatable "
            f"beats fast and abandoned, {name}."
        )
    return (
        f"Missed the goal action today, {name}. One day off doesn't move the trend — "
        "tomorrow's action is deliberately small."
    )


def _claude_message(phase: str, profile: dict, checkin: dict,
                    history: list[dict], strk: dict) -> tuple[str, str] | None:
    """Ask Claude for (coach_message, daily_action). Returns None on any failure
    so the caller falls back to templates."""
    try:
        import anthropic

        client = anthropic.Anthropic()
        recent = "\n".join(
            f"- {c['day']}: slept {c['sleep_hours']:g}h"
            + (f", habit swapped: {'yes' if c['habit_replaced'] else 'no'}"
               if c["habit_replaced"] is not None else "")
            + (f", goal action: {'yes' if c['goal_action_done'] else 'no'}"
               if c["goal_action_done"] is not None else "")
            + (f", note: {c['note']}" if c["note"] else "")
            for c in history[:7]
        ) or "(first check-in)"

        system = (
            "You are Steady, a lifestyle coach for busy young professionals. "
            "Your philosophy: one habit at a time, sleep before everything else, one "
            "small daily action, sustainable pace over speed, zero guilt on lapses. "
            "Never suggest more than one action. Keep the coaching message under 80 "
            "words, warm and direct, no emoji lists or headers."
        )
        prompt = f"""User profile:
- Name: {profile['name']}
- Sleep target: {profile['sleep_target_hours']:g} hours
- Habit they're replacing: {profile['bad_habit']} -> with {profile['replacement_hobby']}
- Long-term goal: {profile['long_term_goal']} ({profile['goal_detail'] or 'no detail'})
- Current phase: {PHASE_LABELS[phase]}
- Streaks: sleep {strk['sleep']}d, habit {strk['habit']}d, goal {strk['goal']}d

Last 7 check-ins (newest first):
{recent}

Today's check-in:
- Slept {checkin['sleep_hours']:g}h
- Habit swapped: {checkin['habit_replaced']}
- Goal action done: {checkin['goal_action_done']}
- Note: {checkin['note'] or '(none)'}

Respond with exactly two lines:
MESSAGE: <your coaching message for today>
ACTION: <the one small action for the next 24 hours, matching the current phase>"""

        response = client.messages.create(
            model="claude-opus-4-8",
            max_tokens=1024,
            thinking={"type": "adaptive"},
            system=[{"type": "text", "text": system,
                     "cache_control": {"type": "ephemeral"}}],
            messages=[{"role": "user", "content": prompt}],
        )
        text = next(b.text for b in response.content if b.type == "text")
        message, action = "", ""
        for line in text.splitlines():
            if line.startswith("MESSAGE:"):
                message = line.removeprefix("MESSAGE:").strip()
            elif line.startswith("ACTION:"):
                action = line.removeprefix("ACTION:").strip()
        if message and action:
            return message, action
        return None
    except Exception:
        return None


def coach_response(profile: dict, checkin: dict, history: list[dict]) -> dict:
    """Produce the coach's reply to a check-in. `history` is newest-first and
    already includes today's check-in."""
    phase = determine_phase(history, profile["sleep_target_hours"])
    strk = streaks(history, profile["sleep_target_hours"])

    result = None
    if os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_AUTH_TOKEN"):
        result = _claude_message(phase, profile, checkin, history, strk)
    if result is None:
        result = (
            _fallback_message(phase, profile, checkin, strk),
            _default_action(phase, profile),
        )

    message, action = result
    return {
        "phase": phase,
        "phase_label": PHASE_LABELS[phase],
        "streaks": strk,
        "coach_message": message,
        "daily_action": action,
    }
